// make_excel.js
// npm install xlsx
import XLSX from "xlsx";

// 1) Define the rows: project name, specialization (lowercase), type ("Software"|"Hardware")
const rows = [
  ["Chat Bot For Food Delivery","web development","Software"],
  ["Rainfall Prediction Model In Chennai City By Using Ml","ai/ml","Software"],
  ["Multimodal Imaging-Based Survival Prediction In Non-Small-Cell Lung Cancer Using Ct And Pet Scans","ai/ml","Software"],
  ["Neurosense: Ai-Based Early Detection Of Neurological Disorders Using Voice And Gait Analysis","ai/ml","Software"],
  ["Temporal Simulation Of Tumor Progression In Mammograms Via Gan-Based Modeling","ai/ml","Software"],
  ["Design And Development Of Context Aware Multicriteria Based Recommender System","ai/ml","Software"],
  ["Fake News Detection Using Machine Learning","ai/ml","Software"],
  ["Profile-Curve Driven 3D Bead Weaving Using Raw Stitch Pattern Generation","software engineering","Software"],
  ["Ai Powered Summarization & Visualization Of Annual Reports Using Multimodal Deep Learning","ai/ml","Software"],
  ["Multimodality Emotion Detection For Diet Recommendation System Using Transformers","ai/ml","Software"],
  ["An Automated Agentic Ai Framework For Proactive Chronic Disease Care With N8N Integration","ai/ml","Software"],
  ["Vehicleguard: A Proactive, Ai-Enhanced Driver Security And Assistance System","iot","Hardware"],
  ["An Ai-Ml Framework For Identifying Academic Malpractice","ai/ml","Software"],
  ["Multi Disease Chest X-Ray Classifier With Explainable Ai","ai/ml","Software"],
  ["Medical Chatbot","ai/ml","Software"],
  ["Crowdshield: An Intelligent, Context-Aware Crowd Safety System","iot","Hardware"],
  ["Satilite Based Crop Health Monitoring System","iot","Hardware"],
  ["Ensemble Deep Learning Approaches For Enhanced Image-Based Classification Of Windows Malware","cyber security","Software"],
  ["Real-Time 3D Object Detection With Lidar–Camera Fusion Using Kitti Dataset","ai/ml","Software"],
  ["Rain Water Prediction Using Arisma+Lstm","ai/ml","Software"],
  ["Personalized Tourist Recommendation System With Health Awareness","ai/ml","Software"],
  ["Nebulacrypt Context Aware Evolving Encryption System","cyber security","Software"],
  ["Smart Forest Defender: Solar-Powered Iot Solution For Fire, Smoke, And Security Alerts","iot","Hardware"],
  ["Multimodal Fruit Spoilage Detection System","ai/ml","Software"],
  ["Ai-Based Virtual Assistant For Vehicle Rental Automation","web development","Software"],
  ["Protoverse Ai: Agentic Ai-Powered Prototyping, From Idea To Clickable Ui.","software engineering","Software"],
  ["Cardioguard: A Real-Time, Ai-Powered Workout Monitoring And Anomaly Detection System For Enhanced Gym Safety","iot","Hardware"],
  ["My Auction – Digital Bidding App","web development","Software"],
  ["Tricky Phones: Tamil Phoneme Feedback Pronunciation System","ai/ml","Software"],
  ["Gridmind – Learning To Power Resilience(Rl-Based Virtual Energy Transfer For Energyefficient Solar)","ai/ml","Software"],
  ["Quantum Cryptography-Based Intelligent Traffic Management And Chain Collision Prevention In Vanets","cyber security","Hardware"],
  ["Unified Transformer-Based Model For Multi-Crop Plant Disease Diagnosis","ai/ml","Software"],
  ["Unified Vision-Based Deep Learning Framework For Real-Time Weed Segmentation, Crop Classification, Growth Stage Estimation, And Health Monitoring In Precision Agriculture","ai/ml","Software"],
  ["Keratoconus Eye Disease Detection Using Deep Learning","ai/ml","Software"],
  ["Gym Workout Recognition And Posture Quality Detection Using Deep Learning","ai/ml","Software"],
  ["Emotion Aware Voice Based Chatbot For Visually Impaired Users","ai/ml","Software"],
  ["Ransomware Detection Using Ml","cyber security","Software"],
  ["Ai-Based Mobile Companion For Scam Link Detection","cyber security","Software"],
  ["Privacy-Preserving Ai Framework For Medical Imaging Via Hybrid Chaotic Homomorphic Encryption","cyber security","Software"],
  ["Zero Watermarking For Image Authentication","cyber security","Software"],
  ["Framework For Real-Time Plant Disease Detection Using Lightweight Deep Learning On Edge Devices","ai/ml","Hardware"],
  ["Eye Effect Detection","ai/ml","Software"],
  ["Atm Biometric Machine Using Deepface","cyber security","Hardware"],
  ["Medimate - An Ai Health Companion","ai/ml","Software"],
  ["Ai-Based Mental Health Monitoring And Assessment System Chatbot","ai/ml","Software"],
  ["Multimodal Spectral Fusion Approach For Milk Quality Analysis","ai/ml","Hardware"],
  ["Vision Transfer And Harris Hawk Optimization Based Explainable Acute Lymphoblastic Leukemia","ai/ml","Software"],
  ["Quantum-Inspired Unsupervised Detection Of Financial Fraud In Transaction Logs Using Kernel Methods","ai/ml","Software"],
  ["An Al-Driven Study On Screen Time And Its Cognitive, Emotional, And Behavioral Impact On Children And Adolescents.","data science","Software"],
  ["Fertilizer Recommendation","ai/ml","Software"],
  ["Smartbug: An Ai Powered Bug Classification System","ai/ml","Software"],
  ["Protocol Design On Multi-Party Key Exchange Using Pqc","cyber security","Software"],
  ["Interpreter In C","software engineering","Software"],
  ["Advanced Cancer Detection From Microscopic Tissue Images Using Hybrid Cnn - Vision Transformer Model","ai/ml","Software"],
  ["Iot-Based Metal Surface Defect Detection Using Deep Learning","iot","Hardware"],
  ["Multimodal Edge-Ai Enabled Autonomous Night Patrol Rover For Rat And Intruder Detection With Real-Time Theft Alerts","iot","Hardware"],
  ["Ai-Driven Skin Profile Analyzer For Chemical Suitability In Skincare Products","ai/ml","Software"],
  ["Ai Based Seat Adjustment System","iot","Hardware"],
  ["Medibot-Your Personal Ai Health Companion","ai/ml","Software"],
  ["Agentive Ai For Personalized Smart Healthcare","ai/ml","Software"],
  ["Stray Dogs Menace Management","iot","Hardware"],
  ["Spectrogram-Based Classification Of Epileptiform Activity In Eeg Signals","ai/ml","Software"],
  ["Adaptive Reinforcement Learning For Automated Code Repair: Integrating Meta Learning And Multi-Dimensional Evaluation","ai/ml","Software"],
  ["Whatsmind - A Chatting App Customised For Adhd People","web development","Software"],
  ["Input Moderation And Injection Filtering In Large Language Model Via Llamaguard Integration","ai/ml","Software"],
  ["Human Action Recognition In Videos Using Convolutional Neural Networks And Long-Short Term Memory Networks","ai/ml","Software"],
  ["Enhancing Patient Compliance Through Smart Medication Dispensing Bot And Monitoring System","iot","Hardware"],
  ["Soilwalk: An Iot Enabled Smart Slipper System For Real-Time Soil Health Mapping","iot","Hardware"],
  ["Evaluating A Mobile Augmented Reality Application For Cognitive And Daily Living Support In People With Dementia: A Participatory Pilot Study","mobile development","Software"],
  ["Footcare Ai - A Smart System For Foot Health Analysis And Footwear Recommendation","ai/ml","Software"],
  ["Qwenos: Ai-Driven Linux Subsystem, Intelligent System Interaction Using Fine Tuned Large Language Models.","software engineering","Software"],
  ["Automated Radiology Report Generation Using Mambavision Encoder And Gpt-2 Decoder","ai/ml","Software"],
  ["She-Ild - Ai Driven Personal Security System For Women","iot","Hardware"],
  ["Brain Tumor Detection Using Vision Transformer On Mri Scans","ai/ml","Software"],
  ["Campus Food Outlet Automation System With Smart Ordering And Payments","web development","Software"],
  ["A Co-Evolutionary Game-Theoretic And Deep Learning Framework For Adaptive Intrusion Detection In Iot Networks","cyber security","Software"],
  ["Intelligent Legal Classification: Predicting The Relevant Section For Crime Cases","ai/ml","Software"],
  ["Scan Cart: Ai-Driven Retail Navigation And Product Detection","iot","Hardware"],
  ["Intelligent Agriculture Water Management System","iot","Hardware"],
  ["Dermai+: Early Rare Skin Disease Detection Using Smartphone Images With Ai Driven Explainability","ai/ml","Software"],
  ["Sms Translator: A Mobile Application For Indic Regional Languages","mobile development","Software"],
  ["Pricepulse — Time Series Price Tracking And Cross-Platform Comparison With Ai","data science","Software"],
  ["A Smart Iot Device For Air Pollution Monitoring And Prediction.","iot","Hardware"],
  ["Smart Industrial Rover: An Edge And Iot-Based System For Worker Safety And Environmental Monitoring","iot","Hardware"],
  ["Derma Predict : Ai Framework For Skin Disease Progression , Inheritance Risk And Prevention","ai/ml","Software"],
  ["Smart Garage Door Control System Using Browser-Based Face Recognition And Iot Integration","iot","Hardware"],
  ["Hybrid Deep Learning Framework For Intelligent Road Accident Detection","ai/ml","Software"],
  ["Llm Based System For Legal Information Retrieval And Summarization","ai/ml","Software"],
  ["Ai Tutoring Platform For Rural Low-Bandwidth Environments","ai/ml","Software"],
  ["Decision Fusion On Image Analysis And Tympanometry To Detect Eardrum Abnormalities","ai/ml","Software"],
  ["Agentic Ai For Remote Patient Monitoring Early Detection Of Patient Deterioration In Chronic Disease Management","ai/ml","Software"],
  ["Uniagent:Mcp-Driven Agentic Rag Framework For Intelligent University Assistance And Automation","ai/ml","Software"],
  ["South Indian Meal Calorie Estimator Using Image Recognition","ai/ml","Software"],
  ["Ai Powered Plastic Waste To Road Repair Optimization","ai/ml","Software"],
  ["Agentic Rag With Model Context Protocol For Real-Time Multi-Jurisdictional Legal Reasoning In Indian Law","ai/ml","Software"],
  ["Smart Assistive System For Medication Information Retrieval And Braille Conversion","iot","Hardware"],
  ["Water Resources Identification In Barren Lands Using Deep Learning Techniques","ai/ml","Software"],
  ["Neuromed Patterns: Real-Time Adverse Event Forecasting Using Eeg And Wearables","ai/ml","Hardware"],
  ["Comparative Analysis Of Hybrid And Traditional Models For Stock Forecasting","data science","Software"],
  ["Clinical Text Summarisation","ai/ml","Software"],
  ["Retrieval-Augmented Generation (Rag) For Enhanced Question-Answering Systems","ai/ml","Software"],
  ["A Real-Time And Personalized Mess Scheduling App","web development","Software"],
  ["Ai-Based Forecasting Of Cognitive Fatigue In Professional Mobility Events","ai/ml","Software"],
  ["Iot-Enabled Anti-Bedsores Monitoring System For Bedridden Patients","iot","Hardware"],
  ["Brain Tumor Detection Using Vgg16","ai/ml","Software"],
  ["Intelligent Attendance Management System With Security, Engagement Analysis And Homomorphic Encryption","cyber security","Software"],
  ["Occulsar - Under Water Human Detection For Search And Rescue Operations","ai/ml","Hardware"],
  ["Human Pose Estimation Using Deep Learning Models","ai/ml","Software"],
  ["Pricepulse – E-Commerce Price Tracker & Smart Comparator","data science","Software"],
  ["Helmet Aware Speed Limiter For Motorcycles","iot","Hardware"],
  ["Wood Boring Pest Detection Using Acoustic Signals","ai/ml","Hardware"],
  ["Alzheimer’s Disease Classification Based On Mri Images Using Vision Transformer Base/14 With Dinov2","ai/ml","Software"],
  ["Multi-Agent Speech-To-Speech Autonomous Customer Support Ai","ai/ml","Software"],
  ["A System To Predict White Spot Disease Susceptibility In Shrimps Using Machine Learning And Deep Learning Models.","ai/ml","Software"],
  ["Legal Document Summarization Using Llm","ai/ml","Software"],
  ["Universal In-App Ai Assistant","ai/ml","Software"],
  ["Breatheai: A Generative Ai-Powered System For Proactive Respiratory Health Monitoring Using Air Quality Analytics","ai/ml","Hardware"],
  ["Developing A Machine Learning Based Coastal Erosion Risk Map For A Selected Indian Coastal Region Using Open-Source Remote Sensing Data","data science","Software"],
  ["Query-Focused Video Summarization Via Referred Video Object Segmentation And Multimodal Tracking Transformers","ai/ml","Software"],
  ["Zen-Sense: An Emotion-Aware Meditation Platform With Machine Learning-Driven Real-Time Biofeedback","ai/ml","Software"],
  ["Text To Isl Video Generation","ai/ml","Software"],
  ["Explainable Ai For Early Diagnosis Of Coronary Artery Disease","ai/ml","Software"],
  ["A Computer Vision-Based System For Real-Time Detection Of Parthenium Hysterophorus","ai/ml","Software"],
  ["A Natural Language Processing Framework For Context-Aware Email Tone Transformation","ai/ml","Software"],
  ["Brain Tumor Classification Using Mri Images Using Efficientnet","ai/ml","Software"],
  ["Ai-Based Solar Power Generation Analysis And Anomaly Detection In Indian Renewable Infrastructure","data science","Software"],
  ["Dual Factor Authentication System Combining Face Recognition And Gaze-Based Pin Entry","cyber security","Hardware"],
  ["Vocal Eyes - Handwritten Text Recognition & Speech Conversion System","ai/ml","Software"],
  ["A Secure File Sharing App With Protection Of High-Value Customers After Zero-Day Credential Leakage (Cyberscan Pro)","cyber security","Software"],
  ["Multi-Modal Ensemble Framework For Predicting Drug-Drug Interactions Using Structured And Unstructured Biomedical Data","ai/ml","Software"],
  ["Detecting E-Commerce Fraud Using Machine Learning","cyber security","Software"],
];

// 2) Convert to worksheet (add header)
const header = [["project name","specialization","type"]];
const aoa = header.concat(rows);
const ws = XLSX.utils.aoa_to_sheet(aoa);

// 3) Create workbook and append sheet
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "projects");

// 4) Write the file
XLSX.writeFile(wb, "projects_specialization.xlsx");

console.log("Wrote projects_specialization.xlsx");
